//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramacionWeb_ExamenFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        public int idUser { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Debe proporcionar Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Debe proporcionar Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [DisplayName("Confirmación Password")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string ConfirmPassword { get; set; }
    }
}
